### ISSUE TITLE
No AUR package

### ISSUE THREAD

**Issue by MadMagnetic** [leonmaxx/asus_fanmode-pkg#3]
There is no AUR package and I can't install it via a command like: sudo pacman -U asus_fanmode-0.3.0-2-x86_64.pkg.tar.xz
loading packages...
error: 'asus_fanmode-0.3.0-2-x86_64.pkg.tar.xz': could not find or read package

**Comment by leonmaxx** [comment]
```
git clone https://github.com/leonmaxx/asus_fanmode-pkg
makepkg
sudo pacman -U asus_fanmode-0.3.0-2-x86_64.pkg.tar.xz
```

**Comment by MadMagnetic** [comment]
Thank you a lot!
